config/routes.rb
Rails.application.routes.draw do
  

  resources :locations
  resources :sessions
  resources :buds

  root 'sessions#index'

  scope '/api' do
    scope '/v1' do
      scope '/locations' do
        post '/' => 'api_locations#create'
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bud.rb
class Bud < ApplicationRecord
  belongs_to :session
  has_many :locations
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :bud
end

app/models/session.rb
class Session < ApplicationRecord
  has_many :buds
end

app/controllers/api_locations_controller.rb
class ApiLocationsController < ApplicationController

  skip_before_action :verify_authenticity_token
  before_filter :parse_request

  def create

    session = Session.find_or_create_by(uuid: @json['session']['uuid'])
    session.platform = @json['session']['platform']

    bud = Bud.where(:session_id => session.id, :uuid => @json['bud']['uuid']).first_or_create
    bud.identifier = @json['bud']['identifier']

    location = Location.new
    location.latitude = @json['location']['latitude']
    location.longitude = @json['location']['longitude']
    location.accuracy = @json['location']['accuracy']
    location.bud_id = bud.id

    Session.transaction do
      session.save
      bud.save
      location.save
    end

    render json: session
  end

  def parse_request
    @json = JSON.parse(request.body.read)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/buds_controller.rb
class BudsController < ApplicationController
  before_action :set_bud, only: [:show, :edit, :update, :destroy]

  # GET /buds
  # GET /buds.json
  def index
    @buds = Bud.all
  end

  # GET /buds/1
  # GET /buds/1.json
  def show
  end

  # GET /buds/new
  def new
    @bud = Bud.new
  end

  # GET /buds/1/edit
  def edit
  end

  # POST /buds
  # POST /buds.json
  def create
    @bud = Bud.new(bud_params)

    respond_to do |format|
      if @bud.save
        format.html { redirect_to @bud, notice: 'Bud was successfully created.' }
        format.json { render :show, status: :created, location: @bud }
      else
        format.html { render :new }
        format.json { render json: @bud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buds/1
  # PATCH/PUT /buds/1.json
  def update
    respond_to do |format|
      if @bud.update(bud_params)
        format.html { redirect_to @bud, notice: 'Bud was successfully updated.' }
        format.json { render :show, status: :ok, location: @bud }
      else
        format.html { render :edit }
        format.json { render json: @bud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buds/1
  # DELETE /buds/1.json
  def destroy
    @bud.destroy
    respond_to do |format|
      format.html { redirect_to buds_url, notice: 'Bud was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bud
      @bud = Bud.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bud_params
      params.require(:bud).permit(:identifier, :session_id, :uuid)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude, :accuracy, :bud_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_session, only: [:show, :edit, :update, :destroy]

  # GET /sessions
  # GET /sessions.json
  def index
    @sessions = Session.order(id: :desc)
  end

  # GET /sessions/1
  # GET /sessions/1.json
  def show
  end

  # GET /sessions/new
  def new
    @session = Session.new
  end

  # GET /sessions/1/edit
  def edit
  end

  # POST /sessions
  # POST /sessions.json
  def create
    @session = Session.new(session_params)

    respond_to do |format|
      if @session.save
        format.html { redirect_to @session, notice: 'Session was successfully created.' }
        format.json { render :show, status: :created, location: @session }
      else
        format.html { render :new }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sessions/1
  # PATCH/PUT /sessions/1.json
  def update
    respond_to do |format|
      if @session.update(session_params)
        format.html { redirect_to @session, notice: 'Session was successfully updated.' }
        format.json { render :show, status: :ok, location: @session }
      else
        format.html { render :edit }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    @session.destroy
    respond_to do |format|
      format.html { redirect_to sessions_url, notice: 'Session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session
      @session = Session.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def session_params
      params.require(:session).permit(:platform, :uuid)
    end
end

app/helpers/api_locations_helper.rb
module ApiLocationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buds_helper.rb
module BudsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/api_locations/create.html.erb
<h1>ApiLocations#create</h1>
<p>Find me in app/views/api_locations/create.html.erb</p>

app/views/buds/_form.html.erb
<%= form_for(bud) do |f| %>
  <% if bud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bud.errors.count, "error") %> prohibited this bud from being saved:</h2>

      <ul>
      <% bud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %>
    <%= f.text_field :identifier %>
  </div>

  <div class="field">
    <%= f.label :session_id %>
    <%= f.number_field :session_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buds/edit.html.erb
<h1>Editing Bud</h1>

<%= render 'form', bud: @bud %>

<%= link_to 'Show', @bud %> |
<%= link_to 'Back', buds_path %>

app/views/buds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buds</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th>Session</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buds.each do |bud| %>
      <tr>
        <td><%= bud.identifier %></td>
        <td><%= bud.session_id %></td>
        <td><%= link_to 'Show', bud %></td>
        <td><%= link_to 'Edit', edit_bud_path(bud) %></td>
        <td><%= link_to 'Destroy', bud, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bud', new_bud_path %>

app/views/buds/new.html.erb
<h1>New Bud</h1>

<%= render 'form', bud: @bud %>

<%= link_to 'Back', buds_path %>

app/views/buds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @bud.identifier %>
</p>

<p>
  <strong>Session:</strong>
  <%= @bud.session_id %>
</p>

<%= link_to 'Edit', edit_bud_path(@bud) %> |
<%= link_to 'Back', buds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.css' rel='stylesheet' />

    <style>
    body, html { margin : 0 !important; padding: 0 !important; }
    </style>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :accuracy %>
    <%= f.text_field :accuracy %>
  </div>

  <div class="field">
    <%= f.label :bud_id %>
    <%= f.number_field :bud_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Accuracy</th>
      <th>Bud</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.accuracy %></td>
        <td><%= location.bud_id %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Accuracy:</strong>
  <%= @location.accuracy %>
</p>

<p>
  <strong>Bud:</strong>
  <%= @location.bud_id %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>